@baseUrl = http://localhost:3001
@page = 1
@pageLimit = 5

### GET products
GET {{baseUrl}}/products?page={{page}}&limit={{pageLimit}}

### Create product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100
}

### Get product by id
GET {{baseUrl}}/products/146564
